import { NextUIProvider } from "@nextui-org/react";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import localFont from "next/font/local";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "../app/api/uploadthing/core";
import AddPostUi from "../app/component/AddPostUi";
import Navbar from "../app/component/Navbar";
import { AppWrapper } from '../app/context'; // Ensure correct path
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextSSRPlugin
          routerConfig={extractRouterConfig(ourFileRouter)}
        />
        <AppWrapper>
          <NextUIProvider>
            <Navbar />
             <div className='min-w-max min-h-screen flex items-center justify-center'>
              <div className='lg:w-[60%] min-h-screen w-screen border-x'>
                   {children}
              </div>
               </div>
               <AddPostUi/>
          </NextUIProvider>
        </AppWrapper>
      </body>
    </html>
  );
}
